### ISSUE TITLE
Problema con las entidades

### ISSUE THREAD

**Issue by hditx** [hditx/programacionIII#2]
Se genero bien la base de datos cuando hice el mapeo directo, pero ahora me sale en toda las esntidades en @ Entity me sale error que no lo puede resolver y nada mas.

¿Como puedo resolverlo? @jruitti

**Comment by jruitti** [comment]
Fijate de correr el Create Tables from Entities y subi captura del error que te salga.

**Comment by hditx** [comment]
ya lo solucione, era porque no habia puesto la conexion a la base de datos

**Comment by jruitti** [comment]
Entonces no habias mapeado, jejeje
